# Generated by Django 5.2.7 on 2026-01-09 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remover', '0003_increase_word_length'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='removeword',
            options={'verbose_name': 'Remove phrase', 'verbose_name_plural': 'Remove phrases'},
        ),
    ]
