# Generated by Django 5.2.7 on 2026-01-09 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remover', '0004_access_log'),
        ('remover', '0004_alter_removeword_options'),
    ]

    operations = [
    ]
